#!/usr/bin/env bash

# Directory of this script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PRESET_FILE="${SCRIPT_DIR}/models.ini"
LLAMA_ARGS="
--host 0.0.0.0
--port 8084 
--webui-mcp-proxy
--tools read_file,file_glob_search,grep_search
"

cd $SCRIPT_DIR

llama serve \
    --models-preset "${PRESET_FILE}" \
    --models-max 1 \
    $LLAMA_ARGS "$@"

