#!/usr/bin/env bash

# Directory of this script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

source "$SCRIPT_DIR/utils.sh"

# Helpers
PRESET_FILE="${SCRIPT_DIR}/models.ini"
LOG_FILE="./logs/server-$(date +%Y%m%dT%H%M%S).log"

# Args
LLAMA_ARGS="
--host 0.0.0.0
--port 1234
--webui-mcp-proxy
--tools read_file,file_glob_search,grep_search
--log-prefix
--log-timestamps
--log-colors off
--log-verbosity 4
--log-prompts-dir ./prompts
--models-preset ${PRESET_FILE}
--models-max 1
"

# Main
mkdir -p ./logs
log_step "Starting llama.cpp server"
log_info "Lama.cpp version: $(llama version | head -n 1)"
log_info "Starting with: 'llama serve $LLAMA_ARGS $@' ..." | tr '\n' ' '
echo ""

# Grava um cabeçalho sem cores no log
echo "Lama.cpp version: $(llama version | head -n 1)" > "${LOG_FILE}"
echo "Starting with: 'llama serve $LLAMA_ARGS $@' ..." | tr '\n' ' ' >> "${LOG_FILE}"
echo -e "\n---" >> "${LOG_FILE}"

# Removemos o --log-file do LLAMA_ARGS pois ele dava truncate no arquivo.
# Ao invés disso, usamos o clássico tee -a para jogar na tela e anexar no arquivo.
llama serve $LLAMA_ARGS "$@" 2>&1 | tee -a "${LOG_FILE}"
