[*]
; Save some vulkan pipelines to the desktop
ubatch-size = 32
batch-size = 256
; Save some VRAM to Desktop
n-gpu-layers = 20
ctx-size = 32768
cache-type-k = q8_0
cache-type-v = q8_0

[unsloth/gemma-4-26B-A4B-it-GGUF:UD-Q4_K_XL]
alias = gemma-4-26B-A4B-mtp
hf = unsloth/gemma-4-26B-A4B-it-GGUF:UD-Q4_K_XL
; enable flash attention
flash-attn = on
; unsloth recomendations for coding
temp = 0.6
top-p = 0.95
top-k = 64
; speed things up with MTP
n-gpu-layers = 99
spec-type = draft-mtp
spec-draft-n-max = 2

[unsloth/gemma-4-26B-A4B-it-qat-GGUF:UD-Q4_K_XL]
alias = gemma-4-26B-A4B
hf = unsloth/gemma-4-26B-A4B-it-qat-GGUF:UD-Q4_K_XL
; enable flash attention
flash-attn = on
; unsloth recomendations for coding
temp = 0.6
top-p = 0.95
top-k = 64

[unsloth/Qwen3.6-35B-A3B-MTP-GGUF:UD-Q4_K_XL]
alias = qwen-3.6-35B-A3B
hf = unsloth/Qwen3.6-35B-A3B-MTP-GGUF:UD-Q4_K_XL
; unsloth recomendations for coding
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.00
; speed things up with MTP
spec-type = draft-mtp
spec-draft-n-max = 2
